steps:
  # Instalar as dependências do projeto
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Rodar testes para garantir que tudo está funcionando corretamente
  # (Descomente a linha abaixo se quiser rodar testes)
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['test']

  # Construir o projeto, compilar TypeScript e lidar com JavaScript
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/sipm-stage/sipm-repo/sipm-backend', '.']

  # Fazer push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/sipm-stage/sipm-repo/sipm-backend']

  # Deploy da imagem no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'sipm-backend',
      '--image', 'us-central1-docker.pkg.dev/sipm-stage/sipm-repo/sipm-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'us-central1-docker.pkg.dev/sipm-stage/sipm-repo/sipm-backend'
